# Generated by Django 5.0.1 on 2024-03-17 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectures',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.subject'),
        ),
    ]
