# Generated by Django 5.0.1 on 2024-01-21 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_rename_course_subject_course_id_course_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='course_id',
            field=models.ForeignKey(default='MCA', on_delete=django.db.models.deletion.CASCADE, to='demoapp.course'),
        ),
    ]
