# Generated by Django 5.0.1 on 2024-03-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_qrcodelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordattendance',
            name='latitude',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='recordattendance',
            name='longitude',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
