# Generated by Django 5.0.1 on 2024-01-21 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_alter_subject_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='demoapp.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.course'),
        ),
    ]
