# Generated by Django 5.0.1 on 2024-03-23 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_lectures_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=255)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('reason', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.course')),
            ],
        ),
    ]
