# Generated by Django 5.0.1 on 2024-01-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_alter_course_subjects_alter_subject_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.TextField(max_length=255),
        ),
    ]
